version: "3"
services:
  bot:
    build: .
    environment:
      - DATABASE_URL
      - BOT_TOKEN
      - BOT_STATE
      - GOOGLE_APPLICATION_CREDENTIALS
    logging:
      driver: gcplogs
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "yeet"
      POSTGRES_USER: "bot"
      POSTGRES_DB: "bot"
    logging:
      driver: gcplogs
volumes:
  db_data:
