version: "3"
services:
  bot:
    build: .
    env_file:
      - .env
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - "db_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "yeet"
      POSTGRES_USER: "bot"
      POSTGRES_DB: "bot"

volumes:
  db_data:
